"""Round-trip tests for mwgg_gui/yaml_creator/yaml_io.py (loaded by file
path — see conftest.py), including description handling and unknown-key
(extras) preservation, the sanctioned interim path for hand-written
`triggers:` blocks.
"""
from __future__ import annotations

import textwrap

import pytest

GAME = "Some Game"


# ----- basic round-trip ----------------------------------------------------


def test_round_trip_name_description_options(yaml_io):
    text = yaml_io.form_state_to_yaml(
        "Alice", GAME, {"opt_a": 5, "opt_b": ["x", "y"]}, description="my seed",
    )
    state = yaml_io.yaml_to_form_state(text, GAME)
    assert state["__name__"] == "Alice"
    assert state["__description__"] == "my seed"
    assert state["__options__"] == {"opt_a": 5, "opt_b": ["x", "y"]}
    assert state["__extras__"] == {}
    assert state["__game_extras__"] == {}


def test_blank_description_gets_default(yaml_io):
    state = yaml_io.yaml_to_form_state(
        yaml_io.form_state_to_yaml("Bob", GAME, {}), GAME
    )
    assert state["__description__"] == "Generated by MultiworldGG for Bob"


def test_integral_floats_coerce_to_int(yaml_io):
    text = yaml_io.form_state_to_yaml("A", GAME, {"opt": 3.0})
    state = yaml_io.yaml_to_form_state(text, GAME)
    assert state["__options__"]["opt"] == 3


# ----- extras preservation -------------------------------------------------


def test_top_level_extras_survive_round_trip(yaml_io):
    src = textwrap.dedent(f"""\
        name: Alice
        game: {GAME}
        description: d
        {GAME}:
          opt_a: 1
        triggers:
          - option_category: {GAME}
            option_name: opt_a
            option_result: 1
            options:
              - {GAME}:
                  opt_b: 2
    """)
    state = yaml_io.yaml_to_form_state(src, GAME)
    assert "triggers" in state["__extras__"]

    out = yaml_io.form_state_to_yaml(
        state["__name__"], GAME, state["__options__"],
        description=state["__description__"],
        extras=state["__extras__"],
        game_extras=state["__game_extras__"],
    )
    state2 = yaml_io.yaml_to_form_state(out, GAME)
    assert state2["__extras__"] == state["__extras__"]
    assert state2["__options__"] == {"opt_a": 1}


def test_game_section_extras_split_on_known_options(yaml_io):
    src = textwrap.dedent(f"""\
        name: Alice
        game: {GAME}
        {GAME}:
          opt_a: 1
          plando_items:
            - item: Sword
    """)
    state = yaml_io.yaml_to_form_state(src, GAME, known_options={"opt_a", "opt_b"})
    assert state["__options__"] == {"opt_a": 1}
    assert state["__game_extras__"] == {"plando_items": [{"item": "Sword"}]}

    # Re-emit: unknown game keys come back inside the game section.
    out = yaml_io.form_state_to_yaml(
        "Alice", GAME, state["__options__"], game_extras=state["__game_extras__"]
    )
    state2 = yaml_io.yaml_to_form_state(out, GAME)
    assert state2["__options__"] == {"opt_a": 1, "plando_items": [{"item": "Sword"}]}


def test_no_known_options_keeps_everything_in_options(yaml_io):
    src = textwrap.dedent(f"""\
        name: Alice
        game: {GAME}
        {GAME}:
          opt_a: 1
          mystery_key: 2
    """)
    state = yaml_io.yaml_to_form_state(src, GAME)
    assert state["__options__"] == {"opt_a": 1, "mystery_key": 2}
    assert state["__game_extras__"] == {}


def test_form_options_win_over_stale_game_extras(yaml_io):
    out = yaml_io.form_state_to_yaml(
        "A", GAME, {"opt": 2}, game_extras={"opt": 1, "other": 3}
    )
    state = yaml_io.yaml_to_form_state(out, GAME)
    assert state["__options__"]["opt"] == 2
    assert state["__options__"]["other"] == 3


def test_extras_never_overwrite_reserved_keys(yaml_io):
    out = yaml_io.form_state_to_yaml(
        "A", GAME, {}, extras={"name": "Mallory", "custom_key": 1, GAME: {"x": 1}}
    )
    state = yaml_io.yaml_to_form_state(out, GAME)
    assert state["__name__"] == "A"
    assert state["__options__"] == {}
    assert state["__extras__"] == {"custom_key": 1}


# ----- ParseError paths ----------------------------------------------------


def test_parse_error_on_bad_yaml(yaml_io):
    with pytest.raises(yaml_io.ParseError):
        yaml_io.yaml_to_form_state("a: [unclosed", GAME)


def test_parse_error_on_non_mapping(yaml_io):
    with pytest.raises(yaml_io.ParseError):
        yaml_io.yaml_to_form_state("- just\n- a list\n", GAME)


def test_parse_error_on_missing_game_key(yaml_io):
    with pytest.raises(yaml_io.ParseError):
        yaml_io.yaml_to_form_state("name: A\n", GAME)


def test_parse_error_on_non_mapping_game_section(yaml_io):
    with pytest.raises(yaml_io.ParseError):
        yaml_io.yaml_to_form_state(f"{GAME}: 3\n", GAME)
