<Selector>:
    color: app.theme_cls.inversePrimaryColor

<MDTextField>:
    theme_font_name: "Custom"
    theme_font_style: "Custom"
    font_name: app.theme_cls.font_styles[self.font_style][self.role]["font-name"]
    font_size: app.theme_cls.font_styles[self.font_style][self.role]["font-size"]
    -padding: (dp(4) if not self._leading_icon else dp(42) if self.mode != "filled" else (dp(6) if not self._leading_icon else dp(52)), (self.height / 2.0 - (self.line_height / 2.0) * min(len(self._lines), int(self.height / self.line_height))) + dp(10 if self.mode == "filled" else 0), dp(4) if not self._trailing_icon else self._trailing_icon.texture_size[0] + dp(28), dp(4))
    -height: dp(40)

<MDTextFieldLeadingIcon>:
    theme_icon_color: "Custom"
    icon_color_focus: app.theme_cls.primaryColor
    icon_color_normal: app.theme_cls.onPrimaryColor

<MDTextFieldHintText>:
    theme_font_name: "Custom"
    theme_font_style: "Custom"
    font_name: app.theme_cls.font_styles[self.font_style][self.role]["font-name"]
    font_size: app.theme_cls.font_styles[self.font_style][self.role]["font-size"]

<RecycleView>:
    -bar_width: dp(10)
    -scroll_type: ["bars", "content"]

<MDScrollView>:
    -bar_width: dp(10)
    -scroll_type: ["bars", "content"]