"""
YAML serialization for the YAML creator screen.

Pure functions: no kivy imports, no widget references. The screen owns
the widget tree; this module owns the conversion between a dict of
option values and the YAML text in the live preview pane.

The shape we read/write is the same shape Generate.py consumes:

    name: <player_name>
    game: <game_display_name>
    description: <free text>
    <game_display_name>:
      option_a: value
      option_b:
        - item_1
        - item_2
      option_c:
        choice_a: 25
        choice_b: 25     # weighted form
"""
from __future__ import annotations

import io
import yaml

__all__ = (
    "FormState",
    "ParseError",
    "form_state_to_yaml",
    "yaml_to_form_state",
)


class ParseError(Exception):
    """Raised when the YAML preview pane contains text we can't sync back."""


class FormState(dict):
    """A plain dict subclass; exists so callers can type-hint and so we can
    extend it later without breaking the function signatures."""


def form_state_to_yaml(
    player_name: str,
    game_name: str,
    options: dict,
    description: str = "",
) -> str:
    """Render the current form state as YAML text.

    `options` is a flat dict of {option_name: value}. Values are written as
    their natural YAML form (str, int, bool, list, dict).
    """
    payload = {
        "name": player_name or "Player",
        "game": game_name,
        "description": description or f"Generated by MultiworldGG for {player_name or 'Player'}",
        game_name: {k: _to_yaml_value(v) for k, v in options.items()},
    }
    buf = io.StringIO()
    yaml.safe_dump(
        payload,
        buf,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )
    return buf.getvalue()


def yaml_to_form_state(text: str, game_name: str) -> FormState:
    """Parse YAML text back into a flat option-name -> value dict.

    Raises ParseError on malformed YAML or missing required keys. The form
    pane only updates when this returns cleanly — partial syncs would leave
    the user in an unclear half-state.
    """
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        raise ParseError(f"YAML syntax error: {e}") from e

    if not isinstance(data, dict):
        raise ParseError("Top-level YAML must be a mapping.")

    if game_name not in data:
        raise ParseError(f"Missing top-level key '{game_name}'.")

    game_options = data[game_name]
    if not isinstance(game_options, dict):
        raise ParseError(f"'{game_name}' must be a mapping of options.")

    state = FormState()
    state["__name__"] = data.get("name", "Player")
    state["__description__"] = data.get("description", "")
    state["__options__"] = dict(game_options)
    return state


def _to_yaml_value(value):
    """Coerce a widget's `value` into something yaml.safe_dump accepts.

    Sliders give floats that are really ints; segmented buttons sometimes
    hand back enum names. Keep this tiny — anything fancier belongs in the
    widget's own `value` getter.
    """
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, (list, tuple)):
        return [_to_yaml_value(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _to_yaml_value(v) for k, v in value.items()}
    return value
