<LauncherScreen>:
    size_hint: 1,1
    pos_hint: {"center_x": 0.5, "center_y": 0.5}

<LauncherLayout>:
    size_hint_y: None
    height: Window.height-103
    MDScreenManager:
        id: launcher_screen_manager
        MDScreen:
            id: launcher_content
            md_bg_color: app.theme_cls.backgroundColor
    MDNavigationDrawer:
        id: launcher_nav_drawer
        radius: 0, dp(16), dp(16), 0
        drawer_type: "modal"
        anchor: "left"
        elevation: 10
        md_bg_color: app.theme_cls.surfaceContainerLowColor

        MDBoxLayout:
            orientation: "vertical"
            spacing: dp(8)
            padding: [dp(4), dp(4), dp(4), dp(4)]

            Image:
                source: os.path.join(os.getenv("KIVY_DATA_DIR"), "images", "logo_bg.png")
                size_hint: 1, None
                height: dp(200)
                fit_mode: "scale-down"
                pos_hint: {"center_x": 0.5, "top": 1}
            NavDrawerMenu:
                id: launcher_nav_menu
                MDNavigationDrawerDivider:
                NavDrawerLabel:
                    text: "Launcher"
                LauncherNavDrawerButton:
                    id: launcher_host_button
                    text: "Start/Host Game"
                    icon: "router-network"
                    on_release: app.launcher_screen.host()
                LauncherNavDrawerButton:
                    id: launcher_generate_button
                    text: "Generate Game"
                    icon: "gamepad-square-outline"
                    on_release: app.launcher_screen.generate()
                LauncherNavDrawerButton:
                    id: launcher_patch_button
                    text: "Patch Game"
                    icon: "file-edit"
                    on_release: app.launcher_screen.patch_game()

<LauncherView>:
    id: launcher_view
    server_layout: server_layout
    title_layout: title_layout
    fallback_status_label: fallback_status_label
    module_name: ""
    orientation: 'vertical'
    padding: dp(50), dp(10), dp(50), dp(50)
    MDLabel:
        id: fallback_status_label
        text: root.fallback_status
        size_hint_y: None
        height: dp(40) if self.text else 0
        opacity: 1 if self.text else 0
        halign: 'center'
        theme_font_style: "Custom"
        font_style: "Body"
        role: "medium"
        theme_text_color: "Custom"
        text_color: app.theme_cls.errorColor
    MDBoxLayout:
        orientation: 'vertical'
        spacing: 30
        padding: dp(30)
        theme_bg_color: "Custom"
        md_bg_color: app.theme_cls.surfaceVariantColor
        MDBoxLayout: # Inner padded layout
            orientation: 'vertical'
            spacing: dp(4)
            MDBoxLayout: # Title & Favorites
                id: title_layout
                orientation: 'vertical'
                size_hint_y: None
                height: dp(120)
                MDLabel:
                    size_hint_y: 0.37
                    text: app.qotd()
                    halign: 'center'
                    theme_font_style: "Custom"
                    font_style: "Title"
                    role: "small"
                    theme_text_color: "Custom"
                    text_color: app.theme_cls.onSurfaceVariantColor
            MDBoxLayout: # Game controls | server fields
                orientation: 'horizontal'
                spacing: 10
                MDBoxLayout: # Game controls
                    orientation: 'vertical'
                    spacing: dp(15)
                    padding: 0, dp(40), 0, 0
                    MDBoxLayout:
                        orientation: 'horizontal'
                        spacing: dp(10)
                        height: dp(40)
                        size_hint_y: .3
                        MDBoxLayout:
                            spacing: dp(4)
                            MDLabel:
                                text: 'Text Client'
                                halign: 'center'
                                valign: 'top'
                                theme_font_style: "Custom"
                                font_style: "Body"
                                role: "medium"
                                theme_text_color: "Custom"
                                text_color: app.theme_cls.onSurfaceVariantColor
                            MDCheckbox:
                                pos_hint: {"center_y": 0.55}
                                group: 'client_type'
                                id: text_client_checkbox
                                on_active: app.launcher_screen.set_client_type('text') if self.active else app.launcher_screen.set_client_type('game')
                        MDDivider:
                            orientation: "vertical"
                            theme_divider_color: "Custom"
                            color: app.theme_cls.outlineColor
                        MDBoxLayout:
                            spacing: dp(4)
                            MDLabel:
                                text: 'Universal Tracker'
                                halign: 'center'
                                valign: 'top'
                                theme_font_style: "Custom"
                                font_style: "Body"
                                role: "medium"
                                theme_text_color: "Custom"
                                text_color: app.theme_cls.onSurfaceVariantColor
                            MDCheckbox:
                                pos_hint: {"center_y": 0.55}
                                group: 'client_type'
                                id: universal_tracker_checkbox
                                on_active: app.launcher_screen.set_client_type('universal_tracker') if self.active else app.launcher_screen.set_client_type('game')
                        MDDivider:
                            orientation: "vertical"
                            theme_divider_color: "Custom"
                            color: app.theme_cls.outlineColor
                        MDBoxLayout:
                            spacing: dp(4)
                            MDLabel:
                                text: 'Manual Client'
                                halign: 'center'
                                valign: 'top'
                                theme_font_style: "Custom"
                                font_style: "Body"
                                role: "medium"
                                theme_text_color: "Custom"
                                text_color: app.theme_cls.onSurfaceVariantColor
                            MDCheckbox:
                                pos_hint: {"center_y": 0.55}
                                group: 'client_type'
                                id: manual_checkbox
                                on_active: app.launcher_screen.set_client_type('manual') if self.active else app.launcher_screen.set_client_type('game')
                    MDScrollView:
                        do_scroll_x: False
                        MDBoxLayout:
                            orientation: 'vertical'
                            adaptive_height: True
                            spacing: dp(15)
                            id: game_components_box
                            MDButton:
                                id: connect_button
                                pos_hint: {"center_x": 0.5}
                                on_release: app.launcher_screen.connect()
                                width: dp(200)
                                radius: dp(10)
                                MDButtonText:
                                    theme_text_color: "Custom"
                                    text_color: app.theme_cls.onSurfaceVariantColor
                                    text: 'Connect & Play'
                                    halign: 'center'
                                MDButtonIcon:
                                    icon: "play-network"
                MDBoxLayout: # Middle vertical divider
                    orientation: 'vertical'
                    spacing: dp(5)
                    width: dp(10)
                    size_hint_x: None
                    MDDivider:
                        size_hint_y: .8
                        pos_hint: {"center_y": 0.5}
                        orientation: "vertical"
                        theme_divider_color: "Custom"
                        color: app.theme_cls.outlineColor
                MDBoxLayout: # text fields
                    id: server_layout
                    orientation: 'vertical'
                    pos_hint: {"center_y": 0.5}
                    spacing: dp(15)
                    LauncherAuthTextField:
                        id: server
                        size_hint_x: 0.8
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        text: app.ctx.hostname
                        MDTextFieldLeadingIcon:
                            theme_icon_color: "Custom"
                            icon: 'router-network'
                            icon_color_focus: self.parent.icon_color_focus
                            icon_color_normal: self.parent.icon_color_normal
                        MDTextFieldHintText:
                            text: "Server Address"
                    LauncherAuthTextField:
                        id: port
                        input_filter: 'int'
                        size_hint_x: 0.8
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        text: app.ctx.port
                        MDTextFieldLeadingIcon:
                            theme_icon_color: "Custom"
                            icon: 'numeric'
                            icon_color_focus: self.parent.icon_color_focus
                            icon_color_normal: self.parent.icon_color_normal
                        MDTextFieldHintText:
                            text: "Port"
                    LauncherAuthTextField:
                        id: slot_name
                        size_hint_x: 0.8
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        text: app.ctx.username
                        on_text_validate: app.launcher_screen.connect()
                        MDTextFieldLeadingIcon:
                            theme_icon_color: "Custom"
                            icon_color_focus: self.parent.icon_color_focus
                            icon_color_normal: self.parent.icon_color_normal
                            icon: 'ticket-account'
                        MDTextFieldHintText:
                            text: "Username"
                    LauncherAuthTextField:
                        id: slot_password
                        password: True
                        size_hint_x: 0.8
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        text: app.app_config.get("client", "slot_password", fallback="")
                        on_text_validate: app.launcher_screen.connect()
                        MDTextFieldLeadingIcon:
                            theme_icon_color: "Custom"
                            icon_color_focus: self.parent.icon_color_focus
                            icon_color_normal: self.parent.icon_color_normal
                            icon: 'lock'
                        MDTextFieldHintText:
                            text: "Password"

<LauncherComponentButton>:
    pos_hint: {"center_x": 0.5}
    width: dp(200)
    radius: dp(10)
    MDButtonText:
        theme_text_color: "Custom"
        text_color: app.theme_cls.onSurfaceVariantColor
        text: root.text
        halign: 'center'
    MDButtonIcon:
        icon: root.icon

<LauncherNavDrawerButton>:
    MDNavigationDrawerItemLeadingIcon:
        icon: root.icon
        theme_icon_color: "Custom"
        icon_color: app.theme_cls.onPrimaryContainerColor
    MDNavigationDrawerItemText:
        text: root.text
        shorten: True
        theme_text_color: "Custom"
        text_color: app.theme_cls.onSecondaryContainerColor
    MDNavigationDrawerItemTrailingText:
        text: root.trailing_text
        width: dp(32)
        theme_text_color: "Custom"
        text_color: app.theme_cls.onTertiaryContainerColor

<LauncherGenerateContent>:
    orientation: 'vertical'
    spacing: dp(15)
    adaptive_height: True
    LauncherAuthTextField:
        id: seed
        size_hint_x: 0.8
        pos_hint: {"center_x": 0.5}
        MDTextFieldHintText:
            text: "Seed"
        MDTextFieldLeadingIcon:
            theme_icon_color: "Custom"
            icon_color_focus: self.parent.icon_color_focus
            icon_color_normal: self.parent.icon_color_normal
            icon: 'seed'
    LauncherAuthTextField:
        id: output
        size_hint_x: 0.8
        pos_hint: {"center_x": 0.5}
        MDTextFieldHintText:
            text: "Output Directory"
        MDTextFieldLeadingIcon:
            theme_icon_color: "Custom"
            icon_color_focus: self.parent.icon_color_focus
            icon_color_normal: self.parent.icon_color_normal
            icon: 'folder'

<LauncherHostContent>:
    orientation: 'vertical'
    spacing: dp(15)
    adaptive_height: True
    MDSegmentedButton:
        size_hint_x: 0.8
        pos_hint: {"center_x": 0.5}
        MDSegmentedButtonItem:
            active: True
            on_active: root.set_mode("local") if self.active else None
            MDSegmentButtonLabel:
                text: "Local Host"
        MDSegmentedButtonItem:
            on_active: root.set_mode("upload") if self.active else None
            MDSegmentButtonLabel:
                text: "Upload to multiworld.gg"
    MDBoxLayout:
        id: mode_box
        orientation: 'vertical'
        spacing: dp(15)
        size_hint_y: None
        height: dp(127)
        LauncherAuthTextField:
            id: port
            input_filter: 'int'
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}
            MDTextFieldHintText:
                text: "Port (default: 38281)"
            MDTextFieldLeadingIcon:
                theme_icon_color: "Custom"
                icon_color_focus: self.parent.icon_color_focus
                icon_color_normal: self.parent.icon_color_normal
                icon: 'numeric'
        LauncherAuthTextField:
            id: admin_password
            password: True
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}
            MDTextFieldHintText:
                text: "Remote Admin Password (optional)"
            MDTextFieldLeadingIcon:
                theme_icon_color: "Custom"
                icon_color_focus: self.parent.icon_color_focus
                icon_color_normal: self.parent.icon_color_normal
                icon: 'lock'

<LauncherPatchContent>:
    orientation: 'vertical'
    spacing: dp(15)
    adaptive_height: True
    LauncherAuthTextField:
        id: output
        size_hint_x: 0.8
        pos_hint: {"center_x": 0.5}
        MDTextFieldHintText:
            text: "Output Directory (optional)"
        MDTextFieldLeadingIcon:
            theme_icon_color: "Custom"
            icon_color_focus: self.parent.icon_color_focus
            icon_color_normal: self.parent.icon_color_normal
            icon: 'folder'

<TagChip>:
    type: "filter"
    MDChipText:
        text: root.text
        icon: root.icon

<LauncherAuthTextField>:
    -height: dp(56)
    theme_font_name: "Custom"
    theme_font_style: "Custom"
    theme_icon_color: "Custom"
    theme_text_color: "Custom"
    theme_bg_color: "Custom"
    text_color_focus: app.theme_cls.onSecondaryContainerColor
    text_color_normal: app.theme_cls.onSurfaceVariantColor
    icon_color_focus: app.theme_cls.primaryColor
    icon_color_normal: app.theme_cls.onPrimaryColor
    fill_color_focus: app.theme_cls.surfaceContainerHighestColor
    fill_color_normal: app.theme_cls.surfaceVariantColor
    font_name: app.theme_cls.font_styles[self.font_style][self.role]["font-name"]
    font_size: app.theme_cls.font_styles[self.font_style][self.role]["font-size"]
    mode: "filled"
    write_tab: False
